insert into todo (DONE, target_Date, description, userName) values (true, '2023-06-25', 'Tics of organic origin', 'jhabershaw0');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-02', 'Blood donors, stem cells', 'lcarolan1');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-06-25', 'Tics of organic origin', 'SinghShubham1308');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-02', 'Blood donors, stem cells', 'SinghShubham1308');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-12-14', 'Other open skull fracture with subarachnoid, subdural, and extradural hemorrhage, with loss of consciousness of unspecified duration', 'zcusted2');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-09-13', 'Infection by Histoplasma capsulatum, without mention of manifestation', 'trobus3');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-01-30', 'Other night blindness', 'aschrei4');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-10-06', 'Antineoplastic and immunosuppressive drugs causing adverse effects in therapeutic use', 'nohannigan5');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-03-19', 'Other postoperative functional disorders', 'gwhacket6');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-03-13', 'Subdural hemorrhage following injury with open intracranial wound, with loss of consciousness of unspecified duration', 'tpontefract7');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-05-04', 'Malignant carcinoid tumor of the rectum', 'dmargrie8');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-03-11', 'Other specified anomalies of circulatory system', 'nlamy9');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-07-13', 'Phlebitis and thrombophlebitis of superficial vessels of lower extremities', 'jlackingtona');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-07-28', 'Benign carcinoid tumor of hindgut, not otherwise specified', 'dvogeleinb');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-24', 'Unspecified burn of eye and adnexa', 'aitzhaiekc');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-12-23', 'Superficial thrombophlebitis complicating pregnancy and the puerperium, antepartum condition or complication', 'SinghShubham1308');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-07-07', 'Chronic or unspecified gastric ulcer with hemorrhage and perforation, with obstruction', 'tmcgavine');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-05-14', 'Nervous system complication, unspecified', 'vwraxallf');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-02-08', 'Benign carcinoid tumor of the large intestine, unspecified portion', 'SinghShubham1308');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-12-27', 'Gonococcal infection (acute) of lower genitourinary tract', 'kivensh');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-06-29', 'Personal history of unspecified disease of respiratory system', 'bmealhami');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-05-24', 'Schizoaffective disorder, chronic with acute exacerbation', 'dtodaroj');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-11-13', 'Poisoning and toxic reactions caused by other specified animals and plants', 'mkloserk');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-12-25', 'Other gonococcal infection (acute) of upper genitourinary tract', 'SinghShubham1308');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-03-18', 'Thoracogenic scoliosis', 'bperelm');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-05-01', 'Open fracture of T1-T6 level with complete lesion of cord', 'hribchestern');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-11-16', 'Blister of finger(s), infected', 'loyleyo');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-05-15', 'Cerebellar or brain stem contusion without mention of open intracranial wound, with loss of consciousness of unspecified duration', 'grudloffp');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-11-15', 'Post-osseointegration mechanical failure of dental implant', 'kcolliverq');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-04-09', 'Other infections specific to the perinatal period', 'gethridger');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-10-04', 'Hurricane', 'apughs');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-08-04', 'Hypertrophy of breast', 'tpellamontt');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-04-19', 'Diabetes with other specified manifestations, type II or unspecified type, uncontrolled', 'gbellshamu');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-01-14', 'Neoplasm of unspecified nature of other genitourinary organs', 'ymclauchlinv');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-10-11', 'Open fracture of three ribs', 'fpickettw');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-09-27', 'Other specified disorders of mineral metabolism', 'hwoolastonx');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-03-29', 'Burn [any degree] involving 90 percent or more of body surface with third degree burn, 80-89%', 'ddorkinsy');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-03-04', 'Tuberculosis of vertebral column, bacteriological or histological examination not done', 'eleppoz');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-04-17', 'Other and unspecified water transport accident injuring water skier', 'syeiles10');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-14', 'Tuberculosis of vertebral column, tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture', 'lmariyushkin11');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-08-03', 'Fall from snowboard', 'vmaclaverty12');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-09-02', 'Other combinations of endocrine dysfunction', 'SinghShubham1308');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-04-19', 'Panuveitis', 'skieff14');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-07-15', 'Chronic depressive personality disorder', 'sduncan15');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-03-02', 'Benign neoplasm of pineal gland', 'gkreuzer16');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-21', 'Helminth infection, unspecified', 'rshave17');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-01-26', 'Late effects of cerebrovascular disease, other speech and language deficits', 'amidlane18');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-01-17', 'Other neonatal endocrine and metabolic disturbances', 'fhankinson19');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-05-28', 'Arthropod-borne disease, unspecified', 'cvoice1a');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-10', 'Pyelitis or pyelonephritis in diseases classified elsewhere', 'ndarinton1b');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-05-28', 'Other closed skull fracture without mention of intracranial injury, with loss of consciousness of unspecified duration', 'dshenton1c');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-03-25', 'Other pathological resorption', 'amcguinley1d');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-05-22', 'Closed fracture of vault of skull with subarachnoid, subdural, and extradural hemorrhage, unspecified state of consciousness', 'dnairns1e');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-10-19', 'Spontaneous abortion, complicated by shock, complete', 'nseed1f');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-10-27', 'Tubal pregnancy without intrauterine pregnancy', 'zallcott1g');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-01-14', 'Infection with microorganisms resistant to penicillins', 'genticknap1h');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-05-28', 'Hodgkin''s disease, nodular sclerosis, intra-abdominal lymph nodes', 'rsamme1i');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-09-10', 'Malignant neoplasm associated with transplant organ', 'nsillito1j');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-22', 'Neoplasm of uncertain behavior of liver and biliary passages', 'gstallan1k');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-10-01', 'Hereditary spherocytosis', 'lschubart1l');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-06-04', 'Need for prophylactic vaccination and inoculation against measles-mumps-rubella (MMR)', 'jmartynka1m');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-05-23', 'Pseudopolyposis of colon', 'bbitten1n');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-12-15', 'Multiple closed fractures involving both upper limbs, and upper limb with rib(s) and sternum', 'hmathivet1o');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-09', 'Cracked tooth', 'kgoodman1p');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-05-23', 'Underweight', 'tsapshed1q');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-08-22', 'Other chronic pain', 'SinghShubham1308');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-10-29', 'Portal hypertension', 'kmcramsey1s');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-04-14', 'Allescheriosis [Petriellidosis]', 'lmellonby1t');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-05-13', 'Second hand tobacco smoke', 'hglisane1u');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-11-04', 'Unspecified crystal arthropathy, lower leg', 'hbranche1v');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-08-14', 'Unspecified osteomyelitis, shoulder region', 'hcottem1w');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-06-05', 'Tuberculosis of lung, infiltrative, tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically', 'opatemore1x');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-08-17', 'Abdominal aneurysm without mention of rupture', 'mlaity1y');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-10-19', 'Bipolar I disorder, single manic episode, in full remission', 'okelsell1z');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-11-28', 'Poisoning by cocaine', 'aspurett20');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-01-23', 'Closed fractures involving skull or face with other bones, without mention or intracranial injury, with prolonged [more than 24 hours] loss of consciousness and return to pre-existing conscious level', 'qestcot21');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-29', 'Suicide and self-inflicted injury by military firearms', 'ljaffra22');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-01-28', 'Counseling on injury prevention', 'mmalyan23');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-06-18', 'Other sprains and strains of wrist', 'amusso24');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-02-03', 'Carrier or suspected carrier of group B streptococcus', 'jmack25');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-09-03', 'Infection with drug-resistant microorganisms, unspecified, without mention of multiple drug resistance', 'eraddon26');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-12-11', 'Ulceration of vulva, unspecified', 'gnono27');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-09-01', 'Venous embolism and thrombosis of superficial vessels of lower extremity', 'gfruchon28');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-01-05', 'Recent retinal detachment, partial, with retinal dialysis', 'fbodesson29');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-11-03', 'Superficial foreign body (splinter) of elbow, forearm, and wrist, without major open wound, infected', 'jandreucci2a');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-11-28', 'Female genital mutilation status, unspecified', 'ghalleday2b');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-01-03', 'Open fractures involving skull or face with other bones with subarachnoid, subdural, and extradural hemorrhage, with prolonged [more than 24 hours] loss of consciousness, without return to pre-existing conscious level', 'ahatrick2c');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-11-17', 'Congenital rubella', 'epickburn2d');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-05-19', 'Open wound of hand except finger(s) alone, complicated', 'ggoseling2e');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-03-25', 'Long-term (current) use of other medications', 'dhambric2f');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-11-06', 'Multiple open fractures of hand bones', 'rpickett2g');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-05-07', 'Reverse articulation', 'nmckennan2h');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-04-13', 'Personal history of malignant neoplasm of female genital organ, unspecified', 'chainey2i');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-05-22', 'Other disorders of lens', 'ckulver2j');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-11-09', 'Foreign body in penis', 'thoodspeth2k');
insert into todo (DONE, target_Date, description, userName) values (true, '2024-04-27', 'Variants of migraine, not elsewhere classified, without mention of intractable migraine without mention of status migrainosus', 'alassells2l');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-12-30', 'Paranoid type schizophrenia, subchronic with acute exacerbation', 'linsull2m');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-05-28', 'Cortex (cerebral) laceration without mention of open intracranial wound, with brief [less than one hour] loss of consciousness', 'dherion2n');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-01-03', 'Malignant neoplasm of pancreatic duct', 'hcowitz2o');
insert into todo (DONE, target_Date, description, userName) values (false, '2024-04-17', 'Otalgia, unspecified', 'scossar2p');
insert into todo (DONE, target_Date, description, userName) values (true, '2023-06-05', 'Other primary progressive tuberculosis, unspecified', 'pelcott2q');
insert into todo (DONE, target_Date, description, userName) values (false, '2023-11-16', 'Malignant neoplasm of head, face, and neck', 'aortet2r');
